apiVersion: v1
kind: ReplicationController
metadata:
  name: javawebapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javaappc
        image: dockergeethaacc/java-web-app:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javasvc
  labels:
    app: javaappsvc
spec:
  type: NodePort
  selector:
    app: javaapp
  ports:
  - port: 80
    nodePort: 30000
    targetPort: 8080
